export const GET_MOVIE = 'GET_MOVIE'
export const LAY_DAMH_SACH_HE_THONG_RAP = 'LAY_DAMH_SACH_HE_THONG_RAP'
export const GET_DETAIL_MOVIE = 'GET_DETAIL_MOVIE'

export const LOG_OUT = 'LOG_OUT'
export const LOGIN_STATUS = 'LOGIN_STATUS'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'

export const CLOSE_MODAL = 'CLOSE_MODAL'

export const OPEN_MODAL_SUCCESS = 'OPEN_MODAL_SUCCESS'
export const OPEN_MODAL_WARNING = 'OPEN_MODAL_WARNING'
export const OPEN_MODAL_ERROR = 'OPEN_MODAL_ERROR'
export const OPEN_MODAL_COMFIRM = 'OPEN_MODAL_COMFIRM'

export const OPEN_MODAL_TRAILER = 'OPEN_MODAL_TRAILER'

export const GET_CHI_TIET_PHONG_VE = 'GET_CHI_TIET_PHONG_VE'

export const CHON_GHE = 'CHON_GHE'
export const DAT_VE = 'DAT_VE'

export const THONG_TIN_TAI_KHOAN = 'THONG_TIN_TAI_KHOAN'

export const GET_MOVIE_DETAIL_LOADING = 'GET_MOVIE_DETAIL_LOADING'
export const LOADING = 'LOADING'

export const REQUIRE_CHOOSING_SEAT = 'REQUIRE_CHOOSING_SEAT'
export const USER_BOOKING_FAIL = 'USER_BOOKING_FAIL'
